export interface CityEntry {
  uf: string;
  city: string;
  slug: string;
  region: string;
  population: number;
  populationLabel: string;
  isCapital: boolean;
  marketNote: string;
}

export const CITIES: CityEntry[] = [
  {
    uf: 'sp',
    city: "São Paulo",
    slug: 'sao-paulo',
    region: "Sudeste",
    population: 11451999,
    populationLabel: "cerca de 11,5 milhãoes de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'rj',
    city: "Rio de Janeiro",
    slug: 'rio-de-janeiro',
    region: "Sudeste",
    population: 6211223,
    populationLabel: "cerca de 6,2 milhãoes de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'df',
    city: "Brasília",
    slug: 'brasilia',
    region: "Centro-Oeste",
    population: 2817381,
    populationLabel: "cerca de 2,8 milhãoes de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'ce',
    city: "Fortaleza",
    slug: 'fortaleza',
    region: "Nordeste",
    population: 2428708,
    populationLabel: "cerca de 2,4 milhãoes de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'ba',
    city: "Salvador",
    slug: 'salvador',
    region: "Nordeste",
    population: 2417678,
    populationLabel: "cerca de 2,4 milhãoes de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'mg',
    city: "Belo Horizonte",
    slug: 'belo-horizonte',
    region: "Sudeste",
    population: 2315560,
    populationLabel: "cerca de 2,3 milhãoes de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'am',
    city: "Manaus",
    slug: 'manaus',
    region: "Norte",
    population: 2063689,
    populationLabel: "cerca de 2,1 milhãoes de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'pr',
    city: "Curitiba",
    slug: 'curitiba',
    region: "Sul",
    population: 1773718,
    populationLabel: "cerca de 1,8 milhão de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'pe',
    city: "Recife",
    slug: 'recife',
    region: "Nordeste",
    population: 1488920,
    populationLabel: "cerca de 1,5 milhão de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'go',
    city: "Goiânia",
    slug: 'goiania',
    region: "Centro-Oeste",
    population: 1437366,
    populationLabel: "cerca de 1,4 milhão de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'rs',
    city: "Porto Alegre",
    slug: 'porto-alegre',
    region: "Sul",
    population: 1332845,
    populationLabel: "cerca de 1,3 milhão de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'pa',
    city: "Belém",
    slug: 'belem',
    region: "Norte",
    population: 1303403,
    populationLabel: "cerca de 1,3 milhão de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'sp',
    city: "Guarulhos",
    slug: 'guarulhos',
    region: "Sudeste",
    population: 1291771,
    populationLabel: "cerca de 1,3 milhão de habitantes",
    isCapital: false,
    marketNote: "Mercado grande e competitivo, com espaço para SEO local e operação previsível.",
  },
  {
    uf: 'sp',
    city: "Campinas",
    slug: 'campinas',
    region: "Sudeste",
    population: 1139047,
    populationLabel: "cerca de 1,1 milhão de habitantes",
    isCapital: false,
    marketNote: "Mercado grande e competitivo, com espaço para SEO local e operação previsível.",
  },
  {
    uf: 'ma',
    city: "São Luís",
    slug: 'sao-luis',
    region: "Nordeste",
    population: 1037775,
    populationLabel: "cerca de 1,0 milhão de habitantes",
    isCapital: true,
    marketNote: "Capital com mercado forte, operação urbana intensa e boa aderência a rotinas mais estruturadas.",
  },
  {
    uf: 'al',
    city: "Maceió",
    slug: 'maceio',
    region: "Nordeste",
    population: 957916,
    populationLabel: "cerca de 957.916 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'ms',
    city: "Campo Grande",
    slug: 'campo-grande',
    region: "Centro-Oeste",
    population: 898100,
    populationLabel: "cerca de 898.100 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'rj',
    city: "São Gonçalo",
    slug: 'sao-goncalo',
    region: "Sudeste",
    population: 896744,
    populationLabel: "cerca de 896.744 habitantes",
    isCapital: false,
    marketNote: "Mercado grande e competitivo, com espaço para SEO local e operação previsível.",
  },
  {
    uf: 'pi',
    city: "Teresina",
    slug: 'teresina',
    region: "Nordeste",
    population: 866300,
    populationLabel: "cerca de 866.300 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'pb',
    city: "João Pessoa",
    slug: 'joao-pessoa',
    region: "Nordeste",
    population: 833932,
    populationLabel: "cerca de 833.932 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'sp',
    city: "São Bernardo do Campo",
    slug: 'sao-bernardo-do-campo',
    region: "Sudeste",
    population: 810729,
    populationLabel: "cerca de 810.729 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'rj',
    city: "Duque de Caxias",
    slug: 'duque-de-caxias',
    region: "Sudeste",
    population: 808161,
    populationLabel: "cerca de 808.161 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'rj',
    city: "Nova Iguaçu",
    slug: 'nova-iguacu',
    region: "Sudeste",
    population: 785867,
    populationLabel: "cerca de 785.867 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'rn',
    city: "Natal",
    slug: 'natal',
    region: "Nordeste",
    population: 751300,
    populationLabel: "cerca de 751.300 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'sp',
    city: "Santo André",
    slug: 'santo-andre',
    region: "Sudeste",
    population: 748919,
    populationLabel: "cerca de 748.919 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sp',
    city: "Osasco",
    slug: 'osasco',
    region: "Sudeste",
    population: 728615,
    populationLabel: "cerca de 728.615 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sp',
    city: "Sorocaba",
    slug: 'sorocaba',
    region: "Sudeste",
    population: 723682,
    populationLabel: "cerca de 723.682 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'mg',
    city: "Uberlândia",
    slug: 'uberlandia',
    region: "Sudeste",
    population: 713224,
    populationLabel: "cerca de 713.224 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sp',
    city: "Ribeirão Preto",
    slug: 'ribeirao-preto',
    region: "Sudeste",
    population: 698642,
    populationLabel: "cerca de 698.642 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sp',
    city: "São José dos Campos",
    slug: 'sao-jose-dos-campos',
    region: "Sudeste",
    population: 697054,
    populationLabel: "cerca de 697.054 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'mt',
    city: "Cuiabá",
    slug: 'cuiaba',
    region: "Centro-Oeste",
    population: 650877,
    populationLabel: "cerca de 650.877 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'pe',
    city: "Jaboatão dos Guararapes",
    slug: 'jaboatao-dos-guararapes',
    region: "Nordeste",
    population: 644037,
    populationLabel: "cerca de 644.037 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'mg',
    city: "Contagem",
    slug: 'contagem',
    region: "Sudeste",
    population: 621863,
    populationLabel: "cerca de 621.863 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sc',
    city: "Joinville",
    slug: 'joinville',
    region: "Sul",
    population: 616317,
    populationLabel: "cerca de 616.317 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'ba',
    city: "Feira de Santana",
    slug: 'feira-de-santana',
    region: "Nordeste",
    population: 616272,
    populationLabel: "cerca de 616.272 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'se',
    city: "Aracaju",
    slug: 'aracaju',
    region: "Nordeste",
    population: 602757,
    populationLabel: "cerca de 602.757 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'pr',
    city: "Londrina",
    slug: 'londrina',
    region: "Sul",
    population: 555965,
    populationLabel: "cerca de 555.965 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'mg',
    city: "Juiz de Fora",
    slug: 'juiz-de-fora',
    region: "Sudeste",
    population: 540756,
    populationLabel: "cerca de 540.756 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sc',
    city: "Florianópolis",
    slug: 'florianopolis',
    region: "Sul",
    population: 537211,
    populationLabel: "cerca de 537.211 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'go',
    city: "Aparecida de Goiânia",
    slug: 'aparecida-de-goiania',
    region: "Centro-Oeste",
    population: 527796,
    populationLabel: "cerca de 527.796 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'es',
    city: "Serra",
    slug: 'serra',
    region: "Sudeste",
    population: 520653,
    populationLabel: "cerca de 520.653 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'rj',
    city: "Campos dos Goytacazes",
    slug: 'campos-dos-goytacazes',
    region: "Sudeste",
    population: 483540,
    populationLabel: "cerca de 483.540 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'rj',
    city: "Belford Roxo",
    slug: 'belford-roxo',
    region: "Sudeste",
    population: 483087,
    populationLabel: "cerca de 483.087 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'rj',
    city: "Niterói",
    slug: 'niteroi',
    region: "Sudeste",
    population: 481749,
    populationLabel: "cerca de 481.749 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sp',
    city: "São José do Rio Preto",
    slug: 'sao-jose-do-rio-preto',
    region: "Sudeste",
    population: 480393,
    populationLabel: "cerca de 480.393 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'pa',
    city: "Ananindeua",
    slug: 'ananindeua',
    region: "Norte",
    population: 478778,
    populationLabel: "cerca de 478.778 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'es',
    city: "Vila Velha",
    slug: 'vila-velha',
    region: "Sudeste",
    population: 467722,
    populationLabel: "cerca de 467.722 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'rs',
    city: "Caxias do Sul",
    slug: 'caxias-do-sul',
    region: "Sul",
    population: 463501,
    populationLabel: "cerca de 463.501 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'ro',
    city: "Porto Velho",
    slug: 'porto-velho',
    region: "Norte",
    population: 460434,
    populationLabel: "cerca de 460.434 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'sp',
    city: "Mogi das Cruzes",
    slug: 'mogi-das-cruzes',
    region: "Sudeste",
    population: 451505,
    populationLabel: "cerca de 451.505 habitantes",
    isCapital: false,
    marketNote: "Cidade relevante para expansão regional com foco em agenda, recorrência e produtividade.",
  },
  {
    uf: 'sp',
    city: "Jundiaí",
    slug: 'jundiai',
    region: "Sudeste",
    population: 443221,
    populationLabel: "cerca de 443.221 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'ap',
    city: "Macapá",
    slug: 'macapa',
    region: "Norte",
    population: 442933,
    populationLabel: "cerca de 442.933 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'rj',
    city: "São João de Meriti",
    slug: 'sao-joao-de-meriti',
    region: "Sudeste",
    population: 440962,
    populationLabel: "cerca de 440.962 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Piracicaba",
    slug: 'piracicaba',
    region: "Sudeste",
    population: 423323,
    populationLabel: "cerca de 423.323 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pb',
    city: "Campina Grande",
    slug: 'campina-grande',
    region: "Nordeste",
    population: 419379,
    populationLabel: "cerca de 419.379 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Santos",
    slug: 'santos',
    region: "Sudeste",
    population: 418608,
    populationLabel: "cerca de 418.608 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Mauá",
    slug: 'maua',
    region: "Sudeste",
    population: 418261,
    populationLabel: "cerca de 418.261 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'mg',
    city: "Montes Claros",
    slug: 'montes-claros',
    region: "Sudeste",
    population: 414240,
    populationLabel: "cerca de 414.240 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'rr',
    city: "Boa Vista",
    slug: 'boa-vista',
    region: "Norte",
    population: 413486,
    populationLabel: "cerca de 413.486 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'mg',
    city: "Betim",
    slug: 'betim',
    region: "Sudeste",
    population: 411846,
    populationLabel: "cerca de 411.846 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pr',
    city: "Maringá",
    slug: 'maringa',
    region: "Sul",
    population: 409657,
    populationLabel: "cerca de 409.657 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'go',
    city: "Anápolis",
    slug: 'anapolis',
    region: "Centro-Oeste",
    population: 398869,
    populationLabel: "cerca de 398.869 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Diadema",
    slug: 'diadema',
    region: "Sudeste",
    population: 393237,
    populationLabel: "cerca de 393.237 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Carapicuíba",
    slug: 'carapicuiba',
    region: "Sudeste",
    population: 386984,
    populationLabel: "cerca de 386.984 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pe',
    city: "Petrolina",
    slug: 'petrolina',
    region: "Nordeste",
    population: 386791,
    populationLabel: "cerca de 386.791 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Bauru",
    slug: 'bauru',
    region: "Sudeste",
    population: 379146,
    populationLabel: "cerca de 379.146 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pe',
    city: "Caruaru",
    slug: 'caruaru',
    region: "Nordeste",
    population: 378048,
    populationLabel: "cerca de 378.048 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'ba',
    city: "Vitória da Conquista",
    slug: 'vitoria-da-conquista',
    region: "Nordeste",
    population: 370879,
    populationLabel: "cerca de 370.879 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Itaquaquecetuba",
    slug: 'itaquaquecetuba',
    region: "Sudeste",
    population: 369275,
    populationLabel: "cerca de 369.275 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'ac',
    city: "Rio Branco",
    slug: 'rio-branco',
    region: "Norte",
    population: 364756,
    populationLabel: "cerca de 364.756 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'sc',
    city: "Blumenau",
    slug: 'blumenau',
    region: "Sul",
    population: 361261,
    populationLabel: "cerca de 361.261 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pr',
    city: "Ponta Grossa",
    slug: 'ponta-grossa',
    region: "Sul",
    population: 358371,
    populationLabel: "cerca de 358.371 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'ce',
    city: "Caucaia",
    slug: 'caucaia',
    region: "Nordeste",
    population: 355679,
    populationLabel: "cerca de 355.679 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'es',
    city: "Cariacica",
    slug: 'cariacica',
    region: "Sudeste",
    population: 353491,
    populationLabel: "cerca de 353.491 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Franca",
    slug: 'franca',
    region: "Sudeste",
    population: 352536,
    populationLabel: "cerca de 352.536 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pe',
    city: "Olinda",
    slug: 'olinda',
    region: "Nordeste",
    population: 349976,
    populationLabel: "cerca de 349.976 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Praia Grande",
    slug: 'praia-grande',
    region: "Sudeste",
    population: 349935,
    populationLabel: "cerca de 349.935 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pr',
    city: "Cascavel",
    slug: 'cascavel',
    region: "Sul",
    population: 348051,
    populationLabel: "cerca de 348.051 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'rs',
    city: "Canoas",
    slug: 'canoas',
    region: "Sul",
    population: 347657,
    populationLabel: "cerca de 347.657 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pe',
    city: "Paulista",
    slug: 'paulista',
    region: "Nordeste",
    population: 342167,
    populationLabel: "cerca de 342.167 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'mg',
    city: "Uberaba",
    slug: 'uberaba',
    region: "Sudeste",
    population: 337836,
    populationLabel: "cerca de 337.836 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pa',
    city: "Santarém",
    slug: 'santarem',
    region: "Norte",
    population: 331942,
    populationLabel: "cerca de 331.942 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "São Vicente",
    slug: 'sao-vicente',
    region: "Sudeste",
    population: 329911,
    populationLabel: "cerca de 329.911 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'mg',
    city: "Ribeirão das Neves",
    slug: 'ribeirao-das-neves',
    region: "Sudeste",
    population: 329794,
    populationLabel: "cerca de 329.794 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pr',
    city: "São José dos Pinhais",
    slug: 'sao-jose-dos-pinhais',
    region: "Sul",
    population: 329628,
    populationLabel: "cerca de 329.628 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'rs',
    city: "Pelotas",
    slug: 'pelotas',
    region: "Sul",
    population: 325685,
    populationLabel: "cerca de 325.685 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'es',
    city: "Vitória",
    slug: 'vitoria',
    region: "Sudeste",
    population: 322869,
    populationLabel: "cerca de 322.869 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'sp',
    city: "Barueri",
    slug: 'barueri',
    region: "Sudeste",
    population: 316473,
    populationLabel: "cerca de 316.473 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Taubaté",
    slug: 'taubate',
    region: "Sudeste",
    population: 310739,
    populationLabel: "cerca de 310.739 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Suzano",
    slug: 'suzano',
    region: "Sudeste",
    population: 307429,
    populationLabel: "cerca de 307.429 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'to',
    city: "Palmas",
    slug: 'palmas',
    region: "Norte",
    population: 302692,
    populationLabel: "cerca de 302.692 habitantes",
    isCapital: true,
    marketNote: "Capital com relevância regional e oportunidade clara para posicionamento local.",
  },
  {
    uf: 'ba',
    city: "Camaçari",
    slug: 'camacari',
    region: "Nordeste",
    population: 300372,
    populationLabel: "cerca de 300.372 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'mt',
    city: "Várzea Grande",
    slug: 'varzea-grande',
    region: "Centro-Oeste",
    population: 300078,
    populationLabel: "cerca de 300.078 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Limeira",
    slug: 'limeira',
    region: "Sudeste",
    population: 291869,
    populationLabel: "cerca de 291.869 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Guarujá",
    slug: 'guaruja',
    region: "Sudeste",
    population: 287634,
    populationLabel: "cerca de 287.634 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'ce',
    city: "Juazeiro do Norte",
    slug: 'juazeiro-do-norte',
    region: "Nordeste",
    population: 286120,
    populationLabel: "cerca de 286.120 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'pr',
    city: "Foz do Iguaçu",
    slug: 'foz-do-iguacu',
    region: "Sul",
    population: 285415,
    populationLabel: "cerca de 285.415 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Sumaré",
    slug: 'sumare',
    region: "Sudeste",
    population: 279545,
    populationLabel: "cerca de 279.545 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'rj',
    city: "Petrópolis",
    slug: 'petropolis',
    region: "Sudeste",
    population: 278881,
    populationLabel: "cerca de 278.881 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  },
  {
    uf: 'sp',
    city: "Cotia",
    slug: 'cotia',
    region: "Sudeste",
    population: 274413,
    populationLabel: "cerca de 274.413 habitantes",
    isCapital: false,
    marketNote: "Mercado em crescimento com potencial para páginas locais de aquisição e validação orgânica.",
  }
];

export function getCityEntry(uf: string, city: string) {
  return CITIES.find((entry) => entry.uf === uf && entry.slug === city);
}
